// flow-typed signature: ef4da897fc3969487ae7753debff5c6c
// flow-typed version: <<STUB>>/budo_v^9.2.1/flow_v0.34.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'budo'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'budo' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'budo/bin/cmd' {
  declare module.exports: any;
}

declare module 'budo/lib/budo' {
  declare module.exports: any;
}

declare module 'budo/lib/bundler' {
  declare module.exports: any;
}

declare module 'budo/lib/error-handler' {
  declare module.exports: any;
}

declare module 'budo/lib/file-watch' {
  declare module.exports: any;
}

declare module 'budo/lib/get-ports' {
  declare module.exports: any;
}

declare module 'budo/lib/map-entry' {
  declare module.exports: any;
}

declare module 'budo/lib/middleware' {
  declare module.exports: any;
}

declare module 'budo/lib/parse-args' {
  declare module.exports: any;
}

declare module 'budo/lib/server' {
  declare module.exports: any;
}

declare module 'budo/lib/simple-http-logger' {
  declare module.exports: any;
}

declare module 'budo/lib/tinylr' {
  declare module.exports: any;
}

// Filename aliases
declare module 'budo/bin/cmd.js' {
  declare module.exports: $Exports<'budo/bin/cmd'>;
}
declare module 'budo/index' {
  declare module.exports: $Exports<'budo'>;
}
declare module 'budo/index.js' {
  declare module.exports: $Exports<'budo'>;
}
declare module 'budo/lib/budo.js' {
  declare module.exports: $Exports<'budo/lib/budo'>;
}
declare module 'budo/lib/bundler.js' {
  declare module.exports: $Exports<'budo/lib/bundler'>;
}
declare module 'budo/lib/error-handler.js' {
  declare module.exports: $Exports<'budo/lib/error-handler'>;
}
declare module 'budo/lib/file-watch.js' {
  declare module.exports: $Exports<'budo/lib/file-watch'>;
}
declare module 'budo/lib/get-ports.js' {
  declare module.exports: $Exports<'budo/lib/get-ports'>;
}
declare module 'budo/lib/map-entry.js' {
  declare module.exports: $Exports<'budo/lib/map-entry'>;
}
declare module 'budo/lib/middleware.js' {
  declare module.exports: $Exports<'budo/lib/middleware'>;
}
declare module 'budo/lib/parse-args.js' {
  declare module.exports: $Exports<'budo/lib/parse-args'>;
}
declare module 'budo/lib/server.js' {
  declare module.exports: $Exports<'budo/lib/server'>;
}
declare module 'budo/lib/simple-http-logger.js' {
  declare module.exports: $Exports<'budo/lib/simple-http-logger'>;
}
declare module 'budo/lib/tinylr.js' {
  declare module.exports: $Exports<'budo/lib/tinylr'>;
}
