// flow-typed signature: abb21aca0517ac7e73311f507e04eb20
// flow-typed version: <<STUB>>/easystarjs_v^0.3.0/flow_v0.34.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'easystarjs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'easystarjs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'easystarjs/bin/easystar-0.3.0' {
  declare module.exports: any;
}

declare module 'easystarjs/bin/easystar-0.3.0.min' {
  declare module.exports: any;
}

declare module 'easystarjs/demo/app' {
  declare module.exports: any;
}

declare module 'easystarjs/demo/static/js/async' {
  declare module.exports: any;
}

declare module 'easystarjs/demo/static/js/bootstrap-select' {
  declare module.exports: any;
}

declare module 'easystarjs/demo/static/js/bootstrap-switch' {
  declare module.exports: any;
}

declare module 'easystarjs/demo/static/js/bootstrap.min' {
  declare module.exports: any;
}

declare module 'easystarjs/demo/static/js/easy-star-demo' {
  declare module.exports: any;
}

declare module 'easystarjs/demo/static/js/easystar-0.3.0.min' {
  declare module.exports: any;
}

declare module 'easystarjs/demo/static/js/flatui-checkbox' {
  declare module.exports: any;
}

declare module 'easystarjs/demo/static/js/flatui-radio' {
  declare module.exports: any;
}

declare module 'easystarjs/demo/static/js/jquery-1.8.3.min' {
  declare module.exports: any;
}

declare module 'easystarjs/demo/static/js/jquery-ui-1.10.3.custom.min' {
  declare module.exports: any;
}

declare module 'easystarjs/demo/static/js/jquery.placeholder' {
  declare module.exports: any;
}

declare module 'easystarjs/demo/static/js/jquery.tagsinput' {
  declare module.exports: any;
}

declare module 'easystarjs/demo/static/js/jquery.ui.touch-punch.min' {
  declare module.exports: any;
}

declare module 'easystarjs/demo/static/js/pixi' {
  declare module.exports: any;
}

declare module 'easystarjs/demo/static/js/tweenjs.min' {
  declare module.exports: any;
}

declare module 'easystarjs/karma.conf' {
  declare module.exports: any;
}

declare module 'easystarjs/src/easystar' {
  declare module.exports: any;
}

declare module 'easystarjs/src/instance' {
  declare module.exports: any;
}

declare module 'easystarjs/src/node' {
  declare module.exports: any;
}

declare module 'easystarjs/test/easystartest' {
  declare module.exports: any;
}

declare module 'easystarjs/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'easystarjs/bin/easystar-0.3.0.js' {
  declare module.exports: $Exports<'easystarjs/bin/easystar-0.3.0'>;
}
declare module 'easystarjs/bin/easystar-0.3.0.min.js' {
  declare module.exports: $Exports<'easystarjs/bin/easystar-0.3.0.min'>;
}
declare module 'easystarjs/demo/app.js' {
  declare module.exports: $Exports<'easystarjs/demo/app'>;
}
declare module 'easystarjs/demo/static/js/async.js' {
  declare module.exports: $Exports<'easystarjs/demo/static/js/async'>;
}
declare module 'easystarjs/demo/static/js/bootstrap-select.js' {
  declare module.exports: $Exports<'easystarjs/demo/static/js/bootstrap-select'>;
}
declare module 'easystarjs/demo/static/js/bootstrap-switch.js' {
  declare module.exports: $Exports<'easystarjs/demo/static/js/bootstrap-switch'>;
}
declare module 'easystarjs/demo/static/js/bootstrap.min.js' {
  declare module.exports: $Exports<'easystarjs/demo/static/js/bootstrap.min'>;
}
declare module 'easystarjs/demo/static/js/easy-star-demo.js' {
  declare module.exports: $Exports<'easystarjs/demo/static/js/easy-star-demo'>;
}
declare module 'easystarjs/demo/static/js/easystar-0.3.0.min.js' {
  declare module.exports: $Exports<'easystarjs/demo/static/js/easystar-0.3.0.min'>;
}
declare module 'easystarjs/demo/static/js/flatui-checkbox.js' {
  declare module.exports: $Exports<'easystarjs/demo/static/js/flatui-checkbox'>;
}
declare module 'easystarjs/demo/static/js/flatui-radio.js' {
  declare module.exports: $Exports<'easystarjs/demo/static/js/flatui-radio'>;
}
declare module 'easystarjs/demo/static/js/jquery-1.8.3.min.js' {
  declare module.exports: $Exports<'easystarjs/demo/static/js/jquery-1.8.3.min'>;
}
declare module 'easystarjs/demo/static/js/jquery-ui-1.10.3.custom.min.js' {
  declare module.exports: $Exports<'easystarjs/demo/static/js/jquery-ui-1.10.3.custom.min'>;
}
declare module 'easystarjs/demo/static/js/jquery.placeholder.js' {
  declare module.exports: $Exports<'easystarjs/demo/static/js/jquery.placeholder'>;
}
declare module 'easystarjs/demo/static/js/jquery.tagsinput.js' {
  declare module.exports: $Exports<'easystarjs/demo/static/js/jquery.tagsinput'>;
}
declare module 'easystarjs/demo/static/js/jquery.ui.touch-punch.min.js' {
  declare module.exports: $Exports<'easystarjs/demo/static/js/jquery.ui.touch-punch.min'>;
}
declare module 'easystarjs/demo/static/js/pixi.js' {
  declare module.exports: $Exports<'easystarjs/demo/static/js/pixi'>;
}
declare module 'easystarjs/demo/static/js/tweenjs.min.js' {
  declare module.exports: $Exports<'easystarjs/demo/static/js/tweenjs.min'>;
}
declare module 'easystarjs/karma.conf.js' {
  declare module.exports: $Exports<'easystarjs/karma.conf'>;
}
declare module 'easystarjs/src/easystar.js' {
  declare module.exports: $Exports<'easystarjs/src/easystar'>;
}
declare module 'easystarjs/src/instance.js' {
  declare module.exports: $Exports<'easystarjs/src/instance'>;
}
declare module 'easystarjs/src/node.js' {
  declare module.exports: $Exports<'easystarjs/src/node'>;
}
declare module 'easystarjs/test/easystartest.js' {
  declare module.exports: $Exports<'easystarjs/test/easystartest'>;
}
declare module 'easystarjs/webpack.config.js' {
  declare module.exports: $Exports<'easystarjs/webpack.config'>;
}
