// flow-typed signature: ab4d481b9dd02bb39d3d27c0079fd0ba
// flow-typed version: <<STUB>>/fast-simplex-noise_v^2.2.0/flow_v0.34.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fast-simplex-noise'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'fast-simplex-noise' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'fast-simplex-noise/main' {
  declare module.exports: any;
}

declare module 'fast-simplex-noise/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'fast-simplex-noise/main.js' {
  declare module.exports: $Exports<'fast-simplex-noise/main'>;
}
declare module 'fast-simplex-noise/test.js' {
  declare module.exports: $Exports<'fast-simplex-noise/test'>;
}
