export default {
  "empty": { name: "empty", icon: 0},
  "wood": { name: "wood", icon: 1 },
  "coal": { name: "coal", icon: 2, fireable: true },
  "stone": { name: "stone", icon: 3 },
  "brick": { name: "brick", icon: 13, placeable: true },
  "sand": { name: "sand", icon: 20, placeable: true },
  "rubber": { name: "rubber", icon: 5 },
  "iron": { name: "iron", icon: 7 },
  "saltpeter": { name: "saltpeter", icon: 6 },
  "wood_sword": { name: "wood_sword", icon: 10, damage: 1 },
  "stone_sword": { name: "stone_sword", icon: 14, damage: 2 },
  "iron_sword": { name: "stone_sword", icon: 18, damage: 4 },
  "wood_pick": { name: "wood_pick", icon: 11, efficiency: 3 },
  "stone_pick": { name: "stone_pick", icon: 15, efficiency: 6 },
  "wood_axe": { name: "wood_pick", icon: 12 },
  "tire": { name: "tire", icon: 16 },
  "segway": { name: "segway", icon: 17, rideable: true, placeable: true },
};
